apiVersion: v1
kind: Secret
metadata:
  name: aplicacao-mysql-secrets
  labels:
    app: aplicacao
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: StrongRootPass123!
  MYSQL_DATABASE: aplicacao
  MYSQL_USER: app
  MYSQL_PASSWORD: AppPass123!
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aplicacao-mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vps54480
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aplicacao-mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: aplicacao-mysql-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-mysql-deployment
  labels:
    app: aplicacao-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacao-mysql
  template:
    metadata:
      labels:
        app: aplicacao-mysql
    spec:
      nodeSelector:
        kubernetes.io/hostname: vps54480
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: aplicacao-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aplicacao-mysql-service
  labels:
    app: aplicacao-mysql
spec:
  selector:
    app: aplicacao-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
  labels:
    app: aplicacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacao
  template:
    metadata:
      labels:
        app: aplicacao
    spec:
      nodeSelector:
        kubernetes.io/hostname: vps54480
      volumes:
      - name: app-code
        hostPath:
          path: /home/saas/aplicacao
      - name: nginx-config
        hostPath:
          path: /home/saas/aplicacao/nginx.conf
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 250m
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          readOnly: true
      - name: php
        image: jpcaballeria/php-build:latest
        env:
        - name: DB_HOST
          value: aplicacao-mysql-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: aplicacao-mysql-secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: aplicacao-service
  labels:
    app: aplicacao
spec:
  type: NodePort
  selector:
    app: aplicacao
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
