# Arquivo: fundo-rotativo2.yaml

# --- Deployment para a Aplicação (fundo-rotativo2) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundo-rotativo2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fundo-rotativo2
  template:
    metadata:
      labels:
        app: fundo-rotativo2
    spec:
      # --- SEÇÃO DE VOLUMES CORRIGIDA ---
      volumes:
        # Volume para o código da aplicação (hostPath para diretório está OK)
        - name: app-code
          hostPath:
            path: /home/saas/fundo-rotativo2/app
        # Volume para a config do Nginx (usando o ConfigMap)
        - name: nginx-config-volume
          configMap:
            name: fundo-rotativo2-nginx-config # Nome do ConfigMap criado no Passo 1
      
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # --- SEÇÃO DE MONTAGEM DE VOLUMES DO NGINX CORRIGIDA ---
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        # Monta o ConfigMap como um arquivo chamado 'default.conf'
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf # Mapeia a chave 'nginx.conf' do ConfigMap para o arquivo
          readOnly: true
      - name: php
        image: jpcaballeria/php-build:latest
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html

---
# --- Serviço para a Aplicação (fundo-rotativo2) ---
apiVersion: v1
kind: Service
metadata:
  name: fundo-rotativo2-service
spec:
  type: NodePort
  selector:
    app: fundo-rotativo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80