# --- 1. Segredos para o Banco de Dados (fundo-rotativo) ---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: fundo-rotativo-mysql-secrets
#type: Opaque
#stringData:
#  MYSQL_ROOT_PASSWORD: "C4b4lleri4202@"
#  MYSQL_DATABASE: "fundorotativo.mysql.dbaas.com.br"
#  MYSQL_USER: "fundorotativo"
#  MYSQL_PASSWORD: "C4b4lleri4202@"

---
# --- 2. Volume Persistente para o Banco de Dados (fundo-rotativo) ---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: fundo-rotativo-mysql-pv
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data/mysql-fundo-rotativo"

---
# --- 3. Solicitação de Volume Persistente (fundo-rotativo) ---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: fundo-rotativo-mysql-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi

---
# --- 4. Deployment para o MySQL (fundo-rotativo) ---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: fundo-rotativo-mysql-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: fundo-rotativo-mysql
#  template:
#    metadata:
#      labels:
#        app: fundo-rotativo-mysql
#    spec:
#      containers:
#      - name: mysql
#        image: mysql:8.0
#        envFrom:
#        - secretRef:
#            name: fundo-rotativo-mysql-secrets
#        ports:
#        - containerPort: 3306
#        volumeMounts:
#        - name: mysql-persistent-storage
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: mysql-persistent-storage
#        persistentVolumeClaim:
#          claimName: fundo-rotativo-mysql-pvc

---
# --- 5. Serviço para o MySQL (fundo-rotativo) ---
#apiVersion: v1
#kind: Service
#metadata:
#  name: fundo-rotativo-mysql-service
#spec:
#  selector:
#    app: fundo-rotativo-mysql
#  ports:
#    - protocol: TCP
#      port: 3306
#      targetPort: 3306

---
# --- 6. Deployment para a Aplicação (fundo-rotativo) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundo-rotativo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fundo-rotativo
  template:
    metadata:
      labels:
        app: fundo-rotativo
    spec:
      volumes:
        - name: app-code
          hostPath:
            path: /home/saas/fundo-rotativo2/app
        - name: nginx-config-volume
          hostPath:
            path: /home/saas/fundo-rotativo2/nginx.conf
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
      - name: php
        # Reutilizando a imagem PHP que você já construiu
        image: jpcaballeria/php-build:latest
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html

---
# --- 7. Serviço para a Aplicação (fundo-rotativo) ---
apiVersion: v1
kind: Service
metadata:
  name: fundo-rotativo-service
spec:
  type: NodePort
  selector:
    app: fundo-rotativo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80