# --- 1. Segredos para o Banco de Dados restaurante-qa ---
apiVersion: v1
kind: Secret
metadata:
  name: restaurante-qa-mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "C4b4lleri42024@"
  MYSQL_DATABASE: "saas_app1"
  MYSQL_USER: "app1"
  MYSQL_PASSWORD: "C4b4lleri42024@"

---
# --- 2. Volume Persistente para o Banco de Dados restaurante-qa ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restaurante-qa-mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-restaurante-qa"

---
# --- 3. Solicitação de Volume Persistente restaurante-qa ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurante-qa-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# --- 4. Deployment para o MySQL restaurante-qa ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-qa-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-qa-mysql
  template:
    metadata:
      labels:
        app: restaurante-qa-mysql
    spec:
      nodeSelector:
        kubernetes.io/hostname: vps54480
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: restaurante-qa-mysql-secrets
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: restaurante-qa-mysql-pvc

---
# --- 5. Serviço para o MySQL restaurante-qa ---
apiVersion: v1
kind: Service
metadata:
  name: restaurante-qa-mysql-service
spec:
  selector:
    app: restaurante-qa-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
# --- 6. Deployment para a Aplicação restaurante-qa (Nginx + PHP) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-qa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-qa
  template:
    metadata:
      labels:
        app: restaurante-qa
    spec:
      nodeSelector:
        kubernetes.io/hostname: vps54480
      volumes:
        - name: app-code
          hostPath:
            path: /home/saas/restaurante-qa/app
        - name: nginx-config
          hostPath:
            path: /home/saas/restaurante-qa/nginx.conf
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          readOnly: true
      - name: php
        image: jpcaballeria/php-build:latest
        env:
        - name: DB_HOST
          value: restaurante-qa-mysql-service
        - name: DB_NAME
          value: saas_app1
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: restaurante-qa-mysql-secrets
              key: MYSQL_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: restaurante-qa-mysql-secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
# --- 7. Serviço para a Aplicação restaurante-qa ---
apiVersion: v1
kind: Service
metadata:
  name: restaurante-qa-service
spec:
  type: NodePort
  selector:
    app: restaurante-qa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


