version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    user: "10001:10001"
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - /home/loki/config.yaml:/etc/loki/config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - saas_net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /home/promtail/config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - saas_net

networks:
  saas_net:
    name: saas_net
    external: true

volumes:
  loki_data:
