version: '3.8'

services:
  fundo-rotativo_nginx:
    image: nginx:latest
    container_name: fundo-rotativo_nginx
    restart: unless-stopped
    volumes:
      - /home/saas/fundo-rotativo/app:/var/www/html
      - /home/saas/fundo-rotativo/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - saas_net

  fundo-rotativo_php:
    build: /home/compose/php_config
    container_name: fundo-rotativo_php
    restart: unless-stopped
    volumes:
      - /home/saas/fundo-rotativo/app:/var/www/html
    networks:
      - saas_net

  fundo-rotativo_db:
    image: mysql:8.0
    container_name: fundo-rotativo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "gQT4TmwEnWv6RK0wmmfl"
      MYSQL_DATABASE: "saas_fundo-rotativo"
      MYSQL_USER: "fundo-rotativo"
      MYSQL_PASSWORD: "gQT4TmwEnWv6RK0wmmfl"
    volumes:
      - fundo-rotativo_db_data:/var/lib/mysql
    networks:
      - saas_net

networks:
  saas_net:
    name: saas_net
    external: true

volumes:
  fundo-rotativo_db_data:
